"""empty message

Revision ID: 0d429def4c5b
Revises: 45ba5a9472f3
Create Date: 2017-05-29 09:41:57.211835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d429def4c5b'
down_revision = '45ba5a9472f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'team_id')
    # ### end Alembic commands ###
