"""added facility_id to teams

Revision ID: 300000e7639c
Revises: a3ac553cc397
Create Date: 2017-05-30 15:46:27.802792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300000e7639c'
down_revision = 'a3ac553cc397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('facility_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'facility_id')
    # ### end Alembic commands ###
