"""add relationship between players and team

Revision ID: 38b9bd95362d
Revises: ee975f72bdf7
Create Date: 2017-05-30 13:21:04.973715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b9bd95362d'
down_revision = 'ee975f72bdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    # ### end Alembic commands ###
