"""added city to players

Revision ID: 50c6919281d4
Revises: 0d429def4c5b
Create Date: 2017-05-29 10:31:53.757298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c6919281d4'
down_revision = '0d429def4c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('city', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'city')
    # ### end Alembic commands ###
