"""empty message

Revision ID: 9513a080b611
Revises: 
Create Date: 2017-05-30 17:23:39.441897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9513a080b611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('num_match_scheduled', sa.Integer(), nullable=True),
    sa.Column('num_match_played', sa.Integer(), nullable=True),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('np_sw', sa.Text(), nullable=True),
    sa.Column('expiration', sa.Text(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('defaults', sa.Integer(), nullable=True),
    sa.Column('win_percent', sa.Integer(), nullable=True),
    sa.Column('singles', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('seasons')
    # ### end Alembic commands ###
