"""added names to matches

Revision ID: 95a83417b00e
Revises: fd4676d436ce
Create Date: 2017-05-31 14:05:03.920401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a83417b00e'
down_revision = 'fd4676d436ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('h_1_player_name', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('h_2_player_name', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('v_1_player_name', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('v_2_player_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'v_2_player_name')
    op.drop_column('matches', 'v_1_player_name')
    op.drop_column('matches', 'h_2_player_name')
    op.drop_column('matches', 'h_1_player_name')
    # ### end Alembic commands ###
