"""2nd foreign key

Revision ID: 97ed5808a696
Revises: a16ef41d0fcb
Create Date: 2017-05-30 11:55:43.467922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ed5808a696'
down_revision = 'a16ef41d0fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'leagues', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    # ### end Alembic commands ###
