"""add backrefs league & season

Revision ID: a16ef41d0fcb
Revises: 6223bf3569fb
Create Date: 2017-05-30 11:33:16.640286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ef41d0fcb'
down_revision = '6223bf3569fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'teams', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    # ### end Alembic commands ###
