"""added player_id to players

Revision ID: af3d48257a46
Revises: 50c6919281d4
Create Date: 2017-05-29 10:55:54.892660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3d48257a46'
down_revision = '50c6919281d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'player_id')
    # ### end Alembic commands ###
