"""add relationship between teams & season

Revision ID: ee975f72bdf7
Revises: 97ed5808a696
Create Date: 2017-05-30 12:14:06.806328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee975f72bdf7'
down_revision = '97ed5808a696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'teams', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    # ### end Alembic commands ###
