"""empty message

Revision ID: f2e2b930b1b0
Revises: ff8ae721f852
Create Date: 2017-05-29 14:00:00.044883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e2b930b1b0'
down_revision = 'ff8ae721f852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('season_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'season_id')
    # ### end Alembic commands ###
