"""added matches tables

Revision ID: fd4676d436ce
Revises: add51c0bb27e
Create Date: 2017-05-31 13:32:22.373765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4676d436ce'
down_revision = 'add51c0bb27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('h_1_player_id', sa.Integer(), nullable=True),
    sa.Column('h_2_player_id', sa.Integer(), nullable=True),
    sa.Column('v_1_player_id', sa.Integer(), nullable=True),
    sa.Column('v_2_player_id', sa.Integer(), nullable=True),
    sa.Column('winning_score', sa.Text(), nullable=True),
    sa.Column('winner', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
